#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'superDigit' function below.
#
# The function is expected to return an INTEGER.
# The function accepts following parameters:
#  1. STRING n
#  2. INTEGER k
#

def superDigit(n, k):
    def helper(n, i = 0):
        if len(n) == 1:
            return n
        if i == 0:
            new = k * int(helper(n,1))

            return helper(str(new),1)
        lst = []
        for i in n:
            lst.append(int(i))

        this = str(sum(lst))
        return helper(this,1)
    return helper(str(n))

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    first_multiple_input = input().rstrip().split()

    n = first_multiple_input[0]

    k = int(first_multiple_input[1])

    result = superDigit(n, k)

    fptr.write(str(result) + '\n')

    fptr.close()
